# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-01 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citydict',
            table='CityDict',
        ),
        migrations.AlterModelTable(
            name='courseorg',
            table='CourseOrg',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
