# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-01 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseresource',
            table='CourseResource',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='Lesson',
        ),
        migrations.AlterModelTable(
            name='video',
            table='Video',
        ),
    ]
