# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-01 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursecomment',
            table='CourseComment',
        ),
        migrations.AlterModelTable(
            name='userask',
            table='UserAsk',
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='UserCourse',
        ),
        migrations.AlterModelTable(
            name='userfavorite',
            table='UserFavorite',
        ),
        migrations.AlterModelTable(
            name='usermessage',
            table='UserMessage',
        ),
    ]
