# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-01 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='Banner',
        ),
        migrations.AlterModelTable(
            name='emailverifyrecord',
            table='EmailVerifyRecord',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
